[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
tera = "1"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"